### ISSUE TITLE
can't check location IP address

### ISSUE THREAD

**Issue by muhammadGagah** [cartertemm/text_information#2]
Hi. Recently I had a problem with text information.
When I want to check the location of my IP address, for example
116.206.31.36
There is information like this:
 IPv4 address, retrieving information...
error: HTTP Error 403: Forbidden.
Why did it happen? even though, when I open the web
https://api.ipinfodb.com/v3/ip-city/?key=32ccf9b820f3c7a8c48c62bc3586582ed3b05faedb78ef90249941fa4de2e183&ip=116.206.31.36&format=json
Everything is normal and I can check my IP.

**Comment by cartertemm** [comment]
Hi,

Thanks for bringing this to my attention, glad to know people still find the add-on useful. Unfortunately, the old API underwent some changes that make it impractical for use in this project, so I went ahead and migrated us to another one. See [version 1.2](https://github.com/cartertemm/text_information/releases/tag/v1.2).
